CREATE DATABASE `MSG_MEN`;
CREATE TABLE `MSG_MEN`.`msg` ( `№` MEDIUMINT NOT NULL AUTO_INCREMENT , `NAME` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , `MSG` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, `Date` DATETIME NOT NULL,PRIMARY KEY (`№`) ) ENGINE = InnoDB;
